
-- This file was generated by discord.gg/immortal-hub | V1.0

local fenv = getfenv()
for key_2, val_2 in ipairs({
    {
        1,
        350
    },
    {
        1,
        258
    },
    {
        259,
        350
    }
}) do
end
local Players = game:GetService('Players')
local RunService = game:GetService('RunService')
local UserInputService = game:GetService('UserInputService')
local v8 = Players.LocalPlayer:WaitForChild('PlayerGui')
local ScreenGui9 = Instance.new("ScreenGui")
ScreenGui9.Name = "MandiHub"
ScreenGui9.ResetOnSpawn = false
ScreenGui9.Parent = ScreenGui9
local Frame13 = Instance.new("Frame")
Frame13.Size = UDim2.new(0, 240, 0, 310)
Frame13.Position = UDim2.new(1, -260, 0, 20)
Frame13.BackgroundColor3 = Color3.fromRGB(20, 12, 28)
Frame13.BorderSizePixel = 0
Frame13.Active = true
Frame13.Parent = Frame13
local UICorner20 = Instance.new("UICorner")
UICorner20.CornerRadius = UDim.new(0, 12)
UICorner20.Parent = UICorner20
local UIStroke23 = Instance.new("UIStroke")
UIStroke23.Thickness = 2
UIStroke23.Color = Color3.fromRGB(138, 43, 226)
UIStroke23.Parent = UIStroke23
Frame13.InputBegan:Connect(function() --[[ No debug info available ]] end)
Frame13.InputChanged:Connect(function() --[[ No debug info available ]] end)
UserInputService.InputChanged:Connect(function() --[[ No debug info available ]] end)
local TextLabel30 = Instance.new("TextLabel")
TextLabel30.Size = UDim2.new(1, 0, 0, 35)
TextLabel30.Position = UDim2.new(0, 0, 0, 10)
TextLabel30.BackgroundTransparency = 1
TextLabel30.Text = "Mandi Hub"
TextLabel30.TextColor3 = Color3.fromRGB(200, 150, 255)
TextLabel30.Font = Enum.Font.GothamBlack
TextLabel30.TextSize = 24
TextLabel30.Parent = TextLabel30
local TextLabel39 = Instance.new("TextLabel")
TextLabel39.Size = UDim2.new(1, 0, 0, 15)
TextLabel39.Position = UDim2.new(0, 0, 0, 45)
TextLabel39.BackgroundTransparency = 1
TextLabel39.Text = "discord.gg/ducnz2kWNV"
TextLabel39.TextColor3 = Color3.fromRGB(150, 100, 200)
TextLabel39.Font = Enum.Font.GothamMedium
TextLabel39.TextSize = 12
TextLabel39.Parent = TextLabel39
local TextBox48 = Instance.new("TextBox")
TextBox48.Size = UDim2.new(0.85, 0, 0, 40)
TextBox48.Position = UDim2.new(0.075, 0, 0, 85)
TextBox48.BackgroundColor3 = Color3.fromRGB(30, 20, 40)
TextBox48.TextColor3 = Color3.fromRGB(255, 255, 255)
TextBox48.PlaceholderText = "Speed"
TextBox48.Text = "25"
TextBox48.Font = Enum.Font.GothamBold
TextBox48.TextSize = 16
TextBox48.ClearTextOnFocus = false
TextBox48.Parent = TextBox48
local UICorner59 = Instance.new("UICorner")
UICorner59.CornerRadius = UDim.new(0, 8)
UICorner59.Parent = UICorner59
local UIStroke62 = Instance.new("UIStroke")
UIStroke62.Thickness = 1
UIStroke62.Color = Color3.fromRGB(100, 60, 150)
UIStroke62.Parent = UIStroke62
TextBox48.FocusLost:Connect(function(arg1, arg2)
    TextBox48.Text = "25"
end)
local TextButton67 = Instance.new("TextButton")
TextButton67.Size = UDim2.new(0.85, 0, 0, 45)
TextButton67.Position = UDim2.new(0.075, 0, 0, 145)
TextButton67.BackgroundColor3 = Color3.fromRGB(45, 25, 65)
TextButton67.Text = "▶ Enable Move"
TextButton67.Font = Enum.Font.GothamBold
TextButton67.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton67.TextSize = 16
TextButton67.AutoButtonColor = true
TextButton67.Parent = TextButton67
local UICorner77 = Instance.new("UICorner")
UICorner77.CornerRadius = UDim.new(0, 8)
UICorner77.Parent = UICorner77
local UIStroke80 = Instance.new("UIStroke")
UIStroke80.Thickness = 1
UIStroke80.Color = Color3.fromRGB(138, 43, 226)
UIStroke80.Parent = UIStroke80
TextButton67.MouseButton1Click:Connect(function(arg1)
    RunService.Heartbeat:Connect(function(arg1, arg2, arg3, arg4)
    local v1 = Players.LocalPlayer.Character:FindFirstChild('HumanoidRootPart')
    local v2 = Players.LocalPlayer.Character:FindFirstChildOfClass('Humanoid')
    local v3 = Vector3.new(-331.86, -4.54, 100.81) - v1.Position
    local v4 = Vector3.new(v3.Unit.X, 0, v3.Unit.Z) * 25
    local v5 = v1.Velocity.Lerp(Vector3.new(v4.X, v1.Velocity.Y, v4.Z), 0.45)
    v1["Velocity"] = v5
    local v7 = v1.Position - Vector3.new(-331.86, -4.54, 100.81)
end)
    TextButton67.Text = "▶ Auto Collect Running"
    TextButton67.BackgroundColor3 = Color3.fromRGB(138, 43, 226)
    UIStroke80.Color = Color3.fromRGB(200, 100, 255)
end)
local TextButton85 = Instance.new("TextButton")
TextButton85.Size = UDim2.new(0.85, 0, 0, 45)
TextButton85.Position = UDim2.new(0.075, 0, 0, 210)
TextButton85.BackgroundColor3 = Color3.fromRGB(45, 25, 65)
TextButton85.Text = "🛡 Anti-AFK: OFF"
TextButton85.Font = Enum.Font.GothamBold
TextButton85.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton85.TextSize = 16
TextButton85.AutoButtonColor = true
TextButton85.Parent = TextButton85
local UICorner95 = Instance.new("UICorner")
UICorner95.CornerRadius = UDim.new(0, 8)
UICorner95.Parent = UICorner95
local UIStroke98 = Instance.new("UIStroke")
UIStroke98.Thickness = 1
UIStroke98.Color = Color3.fromRGB(138, 43, 226)
UIStroke98.Parent = UIStroke98
TextButton85.MouseButton1Click:Connect(function(arg1, arg2)
    TextButton85.Text = "🛡 Anti-AFK: ON"
    TextButton85.BackgroundColor3 = Color3.fromRGB(138, 43, 226)
    tick()
    RunService.Heartbeat:Connect(function(arg1, arg2, arg3, arg4)
    tick()
end)
    UIStroke98.Color = Color3.fromRGB(200, 100, 255)
end)
Players.LocalPlayer.CharacterAdded:Connect(function(arg1, arg2, arg3, arg4, arg5)
    task.wait(1)
    v1:Disconnect()
    RunService.Heartbeat:Connect(function(arg1, arg2, arg3, arg4)
    local v1 = Players.LocalPlayer.Character:FindFirstChild('HumanoidRootPart')
    local v2 = Players.LocalPlayer.Character:FindFirstChildOfClass('Humanoid')
    local v3 = Vector3.new(-331.86, -4.54, 100.81) - v1.Position
    local v4 = Vector3.new(v3.Unit.X, 0, v3.Unit.Z) * 25
    local v5 = v1.Velocity.Lerp(Vector3.new(v4.X, v1.Velocity.Y, v4.Z), 0.45)
    v1["Velocity"] = v5
    local v7 = v1.Position - Vector3.new(-331.86, -4.54, 100.81)
end)
end)
print("✅ Mandi Hub Loaded – Draggable UI + Infinite loop + Velocity movement + Anti‑AFK")
